enum EntityEnum {
  films
  people
  planets
  species
  starships
  vehicles
}

type ImageEntity {
  width: Int
  height: Int
  placeholderPath: String
  imageUrl: String
}
type FilmAssociations {
  species: [Species]
  starships: [Starship]
  vehicles: [Vehicle]
  characters: [Person]
  planets: [Planet]
}

type FilmAttributes {
  episodeID: Int
  openingCrawl: String
  director: String
  producers: [String]
  releaseDate: String
}

type Film implements Node {
  id: ID!
  name: String
  entity: EntityEnum
  imageEntity: ImageEntity
  attributes: FilmAttributes
  associations: FilmAssociations
}

type Query {
  allFilms(search: String, offset: Int, limit: Int): [Film]
  film(id: ID): Film
}
