type FilmDetails {
  species: [Species]
  starships: [Starship]
  vehicles: [Vehicle]
  characters: [Person]
  planets: [Planet]
}

type Film implements Node {
  id: ID!
  name: String
  imageUrl: String
  episodeID: Int
  openingCrawl: String
  director: String
  producers: [String]
  releaseDate: String
  created: String
  edited: String
  details: FilmDetails
}

type Query {
  allFilms(search: String, offset: Int, limit: Int): [Film]
  film(id: ID, filmID: ID): Film
}
