type Person implements Node {
  id: ID!
  name: String
  imageUrl: String
  birthYear: String
  eyeColor: String
  gender: String
  hairColor: String
  height: Int
  mass: Int
  skinColor: String
  homeworld: Planet
  films: [Film]
  species: [Species]
  starships: [Starship]
  vehicles: [Vehicle]
  created: String
  edited: String
}

type Query {
  allPeople(search: String, offset: Int, limit: Int): [Person]
  person(id: ID, personID: ID): Person
}
