union Item = Person | Film | Planet | Species | Vehicle | Starship

type AllReturn {
  count: Int
  page: Int
  results: [Item]
}

interface Node {
  id: ID!
  name: String
  entity: EntityEnum
  imageEntity: ImageEntity
}

type RootQuery {
  node(id: ID!): Node
}
