type Species implements Node {
  id: ID!
  name: String
  imageUrl: String
  classification: String
  designation: String
  averageHeight: Float
  averageLifespan: Int
  eyeColors: [String]
  hairColors: [String]
  skinColors: [String]
  language: String
  homeworld: Planet
  people: [Person]
  films: [Film]
  created: String
  edited: String
}

type Query {
  allSpecies(search: String, offset: Int, limit: Int): [Species]
  species(id: ID, speciesID: ID): Species
}
