type StarshipsAssociations {
  pilots: [Person]
  films: [Film]
}

type StarshipsAttributes {
  model: String
  starshipClass: String
  manufacturers: [String]
  costInCredits: String
  length: String
  crew: String
  passengers: String
  maxAtmospheringSpeed: String
  hyperdriveRating: String
  MGLT: String
  cargoCapacity: String
  consumables: String
}

type Starship implements Node {
  id: ID!
  name: String
  entity: EntityEnum
  imageEntity: ImageEntity
  attributes: StarshipsAttributes
  associations: StarshipsAssociations
}

type Query {
  allStarships(search: String, offset: Int, limit: Int): AllReturn
  starship(id: ID): Starship
}
