type Starship implements Node {
  name: String
  model: String
  starshipClass: String
  manufacturers: [String]
  costInCredits: Float
  length: Float
  crew: String
  passengers: String
  maxAtmospheringSpeed: Int
  hyperdriveRating: Float
  MGLT: Int
  cargoCapacity: Float
  consumables: String
  pilots: [Person]
  films: [Film]
  created: String
  edited: String
  id: ID!
  imageUrl: String
}

type Query {
  allStarships(search: String, offset: Int, limit: Int): [Starship]
  starship(id: ID, starshipID: ID): Starship
}
