type Vehicle implements Node {
  id: ID!
  name: String
  imageUrl: String
  model: String
  vehicleClass: String
  manufacturers: [String]
  costInCredits: Int
  length: Float
  crew: String
  passengers: String
  maxAtmospheringSpeed: Int
  cargoCapacity: Int
  consumables: String
  pilots: [Person]
  films: [Film]
  created: String
  edited: String
}

type Query {
  allVehicles(search: String, offset: Int, limit: Int): [Vehicle]
  vehicle(id: ID, vehicleID: ID): Vehicle
}
