type VehicleAttributes {
  model: String
  vehicleClass: String
  manufacturers: [String]
  costInCredits: String
  length: String
  crew: String
  passengers: String
  maxAtmospheringSpeed: String
  cargoCapacity: String
  consumables: String
}

type VehicleAssociations {
  pilots: [Person]
  films: [Film]
}

type Vehicle implements Node {
  id: ID!
  name: String
  entity: EntityEnum
  imageEntity: ImageEntity
  attributes: VehicleAttributes
  associations: VehicleAssociations
}

type AllReturnVehicle {
  count: Int
  results: [Vehicle]
}

type Query {
  allVehicles(search: String, offset: Int, limit: Int): AllReturnVehicle
  vehicle(id: ID): Vehicle
}
